DROP DATABASE IF EXISTS CINECLUB
USE BANCO
CREATE DATABASE CINECLUB
GO

USE CINECLUB
GO
CREATE TABLE CLIENTE
(
    ID_CLI INT IDENTITY(1,1) PRIMARY KEY,
    NOM_CLI NVARCHAR(50) NOT NULL,
    APE_CLI NVARCHAR(50) NOT NULL,
    CORREO_CLI NVARCHAR(100) NOT NULL,
    CONTRA_CLI VARBINARY(256) NOT NULL,
)

GO

CREATE TABLE PELICULA
(
    ID_PEL NVARCHAR(4) NOT NULL PRIMARY KEY,
    NOM_PEL NVARCHAR(50) NOT NULL,
    GEN_PEL NVARCHAR(50) NOT NULL,
    DUR_PEL INT NOT NULL,
    DES_PEL NVARCHAR(500) NOT NULL,
    FECHA_PEL DATE NOT NULL,
    DIR_PEL NVARCHAR(50) NOT NULL,
    CARATULA NVARCHAR(200) NOT NULL,
    CALI_PEL DECIMAL(2,1)
)   

GO

CREATE TABLE SALAS
(
    ID_SALA INT IDENTITY(1,1) PRIMARY KEY,
    NUM_ASIENTOS INT NOT NULL,
)

GO

CREATE TABLE HORARIO
(
    ID_HOR INT IDENTITY(1,1) PRIMARY KEY,
    ID_PEL NVARCHAR(4) NOT NULL,
    HORA TIME NOT NULL,
    ID_SALA INT NOT NULL,
    FECHA DATE NOT NULL,
    FOREIGN KEY (ID_PEL) REFERENCES PELICULA(ID_PEL),
    FOREIGN KEY (ID_SALA) REFERENCES SALAS(ID_SALA)
)

GO

CREATE TABLE ASIENTOS
(
    ID_ASI NVARCHAR(3) NOT NULL,
    ID_SALA INT NOT NULL,
    ESTADO BIT NOT NULL,
    -- 0 para 'LIBRE', 1 para 'OCUPADO'
    PRIMARY KEY (ID_ASI, ID_SALA),
    FOREIGN KEY (ID_SALA) REFERENCES SALAS(ID_SALA)
)

GO

CREATE TABLE RESERVA
(
    ID_RES INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLI INT NOT NULL,
    ID_HOR INT NOT NULL,
    NUM_RES INT NOT NULL,
    ID_ASI NVARCHAR(3) NOT NULL,
    ID_SALA INT NOT NULL,
    PRECIO DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (ID_CLI) REFERENCES CLIENTE(ID_CLI),
    FOREIGN KEY (ID_HOR) REFERENCES HORARIO(ID_HOR),
    FOREIGN KEY (ID_ASI,ID_SALA) REFERENCES ASIENTOS(ID_ASI,ID_SALA)
)

GO
DROP TABLE IF EXISTS ESTADISTICAS_VENTAS
CREATE TABLE ESTADISTICAS_VENTAS
(
    ID_ESTV INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_RES INT NOT NULL,
    MONTO_VEN DECIMAL(5,2) NOT NULL,
    FECHA DATE NOT NULL,
    FOREIGN KEY (ID_RES) REFERENCES RESERVA(ID_RES)
)

DROP TRIGGER IF EXISTS ActualizarEstadisticasVentas
GO
CREATE TRIGGER ActualizarEstadisticasVentas
ON RESERVA
AFTER INSERT
AS
BEGIN
    INSERT INTO ESTADISTICAS_VENTAS
        (ID_RES, MONTO_VEN, FECHA)
    SELECT ID_RES, PRECIO, GETDATE()
    FROM inserted;
END;

INSERT INTO PELICULA
    (ID_PEL, NOM_PEL, GEN_PEL, DUR_PEL, DES_PEL, FECHA_PEL, DIR_PEL, CARATULA, CALI_PEL)
VALUES
    ('KPA4', 'Kung Fu Panda 4', 'Animacion', 90, 'Po y los 5 furiosos se enfrentan a un nuevo enemigo que puede robar los poderes de los maestros de Kung Fu su nombre es La Camaleona, ahora Poo debe enfrensarse al pasado', '2024-03-07', 'Jennifer Yuh Nelson', 'Kpan4.png', 4.8)

DELETE FROM CLIENTE
where ID_CLI = 5
GO
SELECT * FROM PELICULA